<?php
/**
 * Created by PhpStorm.
 * User: yunxi
 * Date: 2019/3/21 0021
 * Time: 16:22
 */

namespace App\Model;


class User extends Base
{
    public $table = 'user';
    public static $user_sex = [1=>'男',2=>'女'];
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public static function edit($where = [],$data = []){
        $data['alter_time'] = time();
        return parent::edit($where,$data);
    }

    public static function __callStatic($method, $parameters)
    {
        //判断是否查询单条数据,如果是则判断缓存内是否有记录
        if($method ==  'getOne'){
            if(isset($parameters[0][self::$pk])){
                $cache_key = str_replace(['table','pk'],[(new self)->table,$parameters[0][self::$pk]],self::$cache_key);
                dump((new self)->table);die;
            }
        }
        return parent::__callStatic($method, $parameters); // TODO: Change the autogenerated stub
    }
}